version: "3.8"
services:
  backend:
    build: ./api
    ports:
      - '8080:8080'
    volumes:
      - ./api:/app
      - /app/node_modules
    env_file:
      - ./env/api.env
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
